<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>tc.oc.occ</groupId>
	<artifactId>Database</artifactId>
	<version>2.0.0-SNAPSHOT</version>
	<name>Database</name>
	<description>A shared database plugin for Overcast Community</description>

	<properties>
		<maven.compiler.release>21</maven.compiler.release>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.bukkit.main>tc.oc.occ.database.Database</project.bukkit.main>
		<project.author>applenick</project.author>
	</properties>

	<distributionManagement>
		<repository>
			<id>pgm-repo-snapshots</id>
			<url>https://repo.pgm.fyi/snapshots</url>
		</repository>
	</distributionManagement>

	<repositories>
		<repository>
			<id>pgm-repo-snapshots</id>
			<name>PGM Repository</name>
			<url>https://repo.pgm.fyi/snapshots</url>
		</repository>
		<repository>
			<id>spigot-repo</id>
			<url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
		</repository>
		<repository>
			<id>aikar</id>
			<url>https://repo.aikar.co/content/groups/aikar/</url>
		</repository>
	</repositories>

	<dependencies>
		<!-- Intersected SportPaper 1.8-Paper 1.21.10 jar -->
		<dependency>
			<groupId>dev.pgm.paper</groupId>
			<artifactId>paper-api</artifactId>
			<version>1.8_1.21.10-SNAPSHOT</version>
			<scope>provided</scope>
		</dependency>

		<!-- Command Framework -->
		<dependency>
			<groupId>co.aikar</groupId>
			<artifactId>acf-bukkit</artifactId>
			<version>0.5.1-SNAPSHOT</version>
		</dependency>

		<!-- MySQL -->
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>4.0.3</version>
		</dependency>

		<!-- Redis -->
		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<version>3.5.1</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>

		<!-- Annotations -->
		<dependency>
			<groupId>org.jspecify</groupId>
			<artifactId>jspecify</artifactId>
			<version>1.0.0</version>
		</dependency>

		<!-- BungeeCord api, same as in Paper 1.21 -->
		<dependency>
			<groupId>net.md-5</groupId>
			<artifactId>bungeecord-api</artifactId>
			<version>1.21-R0.2</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<resources>
			<!-- Include the required plugin.yml and config.yml for Bukkit -->
			<resource>
				<directory>${basedir}/src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
				<configuration>
					<compilerArgs>
						<arg>-parameters</arg> <!-- Required for aikar/commands
						to auto generate syntax -->
					</compilerArgs>
				</configuration>
			</plugin>


			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.1</version>
				<configuration>
					<relocations>
						<relocation>
							<pattern>co.aikar.commands</pattern>
							<shadedPattern>tc.oc.occ.database.acf</shadedPattern>
						</relocation>
					</relocations>
					<createDependencyReducedPom>false</createDependencyReducedPom>
					<minimizeJar>true</minimizeJar>
					<artifactSet>
						<includes>
							<include>co.aikar:*</include>
							<include>com.zaxxer:*</include>
							<include>redis.clients:jedis</include>
							<include>org.apache.commons:commons-pool2</include>
						</includes>
					</artifactSet>
					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>META-INF/**</exclude>
							</excludes>
						</filter>
					</filters>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<!-- Validates that code is properly formatted with Google's code
			style -->
            <plugin>
                <groupId>com.spotify.fmt</groupId>
                <artifactId>fmt-maven-plugin</artifactId>
                <version>2.27</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.google.googlejavaformat</groupId>
                        <artifactId>google-java-format</artifactId>
                        <version>1.27.0</version>
                    </dependency>
                </dependencies>
            </plugin>
		</plugins>
	</build>

</project>
